name: 'nyc_mobility'
version: '1.0.0'
config-version: 2

# Este nombre debe coincidir exactamente con el de profiles.yml
profile: 'nyc_mobility'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuración por defecto para nuestros modelos
models:
  nyc_mobility:
    # Por defecto, dbt creará Vistas en memoria de DuckDB, 
    # excepto que le digamos explícitamente que cree una Tabla.
    materialized: view